name: graaljit

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '22'      # See 'Options' section below for all supported versions
          distribution: 'graalvm' # See 'Options' section below for all available distributions
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Compile 
        run: |
          native-image --target=android-aarch64 --shared --native-compiler-path=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -cp graal.jar:truffle-compiler.jar:collections.jar:words.jar
